FROM python:3.10

RUN mkdir /app
WORKDIR /app

EXPOSE 5000

RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

RUN curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list

RUN exit

RUN apt-get update

RUN ACCEPT_EULA=Y apt-get install -y msodbcsql18

COPY ../api/requirements.txt .

RUN pip install -r requirements.txt

ADD / .

WORKDIR api

CMD [ "uwsgi", "--ini", "app.ini" ]